# Generated by Django 2.2.3 on 2019-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190720_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='güncelleme',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yorum',
            name='onay',
            field=models.BooleanField(default=False),
        ),
    ]
